language: r
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - TOXIPROXYR_SERVER_BIN_PATH=$PWD/.toxiproxy
    - TOXIPROXYR_SERVER_INSTALL=true
